// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
       return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv-g8rp70-WOpgl8lOH9BPe_9ZL5_SlG8',
    appId: '1:952489371666:android:4d47545f8428f910d810cb',
    messagingSenderId: '952489371666',
    projectId: 'tualiadodigital-sigmap',
    databaseURL: 'https://tualiadodigital-sigmap-default-rtdb.firebaseio.com',
    storageBucket: 'tualiadodigital-sigmap.appspot.com',
  );
    static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC6Mc8gFGFyrjlciMh2QpU-Sne61imFxuk",
      authDomain: "tualiadodigital-sigmap.firebaseapp.com",
      databaseURL: "https://tualiadodigital-sigmap-default-rtdb.firebaseio.com",
      projectId: "tualiadodigital-sigmap",
      storageBucket: "tualiadodigital-sigmap.appspot.com",
      messagingSenderId: "952489371666",
      appId: "1:952489371666:web:62c613c1a970a6fbd810cb",
      measurementId: "G-RELXYK8V05"
  );
}
